### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por ID
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### Recuperar todas las peliculas por un genero
GET http://localhost:1234/movies?genre=horror

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

 {
    "title": "The GodFather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.png",
    "genre": [
        "Crime",
        "Drama"
    ]
    
 }
 
### Actualizar una pelicula por ID 
PATCH http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-Type: application/json

 {
    "title": "Pulp Fiction",
    "year": 1990
 }
